"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
NumA = 1
NumB = 2
count = 2
while NumA <= 4000000 and NumB <= 4000000:
	NumA = NumA + NumB
	if NumA % 2 == 0:
		count += NumA
	NumB = NumA + NumB
	if NumB % 2 == 0:
		count += NumB
print (count)