"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""
tri_num = []
pent_num = []
for i in range(1, 100000):
    tri_num.append(i*(i+1)/2)
for i in range(1, 100000):
    pent_num.append(i*(3*i-1)/2)
a = list((set(tri_num).intersection(pent_num)))
print(a[2])
